# Generated by Django 4.2.5 on 2023-10-26 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion1', '0002_clases_tematica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clases',
            name='tematica',
            field=models.CharField(max_length=30),
        ),
    ]
